### ISSUE TITLE
[ Feature request / Fix ] Add an option to create an empty web app template when "failed to fetch title" occurs.

### ISSUE THREAD

**Issue by rionyreva** [Zaedus/spider#14]
When attempting to create a new web app, Spider sometimes encounters an issue where certain URLs result in a "failed to fetch title" error, preventing the app from being created. To improve this experience, I propose adding an option that allows users to create an empty web app template if the automatic title fetch fails.

With this feature, users would be able to:
- Manually input and customize details such as URL, name, and icon when title fetching is unsuccessful.
- Effortlessly add any web page as a web app without being blocked by fetching errors.

Currently, a workaround exists where users can add a functional URL (e.g., https://duckduckgo.com/) to create the app and then manually edit the saved web app to point to the desired URL. Implementing this feature would streamline the process and provide a more user-friendly approach to handling these cases.

**Comment by mambucodev** [comment]
Mentioned this on #13

**Comment by Zaedus** [comment]
Hi, and thank you for the feature request! I've known about this problem, but I wanted to fix it with a more user friendly solution. 

My current plan is to fetch as much metadata as possible, then populate whatever gets returned in a dialog should some of it be inaccurate or not present. 

This will fix the immediate error, but for the future I'd like to use a modal web view to extract the title, icon, and url by letting the user navigate the web page first, and then click "Install" when they're ready (maybe even have the option of using a search engine instead of entering a raw url).

I am a bit busy for the moment, but hopefully I can find some time to sit down and get to work on that first bit.

**Comment by Zaedus** [comment]
The redesigned dialog fixes this issue and boasts some nice QOL improvements. Thanks for the issue. If someone could test it on the dev branch and give me any feedback before I create a new version, that would be really appreciated!

https://github.com/user-attachments/assets/8079e3cf-2c4b-4b52-8fbd-c1869f5aedca
