### ISSUE TITLE
failed to fetch icons

### ISSUE THREAD

**Issue by MakaiHanta** [Zaedus/spider#17]
the most important question is why can't either the app or me as a user give a fuck whether your shitcode got a site icon or not? Why can't you just make a working program?

**Comment by Zaedus** [comment]
Hey Asshole! Thanks for leaving a comment :) I find it interesting you've come all this way when your GitHub account has *no* open source contributions AT ALL. Maybe instead of complaining like a whiny little diaper baby, you make a PR and meaningfully engage with my project. Oh wait! If you actually did engage with my project, you'd notice there are two (2) closed issues (#13 #14) where I address and *solve* this problem. 

Thanks for stopping by though :)
